{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helix.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helix.labels" . | nindent 4 }}
type: Opaque
stringData:
  LISTENBRAINZ_TOKEN: {{ .Values.env.listenbrainz.token | quote }}
  SUBSONIC_BASE_URL: {{ .Values.env.subsonic.baseUrl | quote }}
  SUBSONIC_USERNAME: {{ .Values.env.subsonic.username | quote }}
  SUBSONIC_PASSWORD: {{ .Values.env.subsonic.password | quote }}
{{- end }}
